### ISSUE TITLE
Option menu not working.

### ISSUE THREAD

**Issue by syncinggreen** [Anon-Artist/R3C0Nizer#19]
Options number 10 ,11 ,101 are not working. While entering just a single digit from 1-9 it auto selects and move towards asking domain.

I have not checked thoroughly , pls check entering all the given numbers options if working fine or not.
Thanks

**Comment by Anon-Artist** [comment]
Thanks i was updating and fixing bugs, Please do git clone again, now it is fixed
Thank you and Happy Hacking :100:
