### ISSUE TITLE
feroxbuster download path is wrong

### ISSUE THREAD

**Issue by syncinggreen** [Anon-Artist/R3C0Nizer#20]

**Comment by syncinggreen** [comment]
pls check the scans module wise. There are more issues

**Comment by Anon-Artist** [comment]
I was Working on each modules and fixing bugs and adding new features  :)
it was all sudden feroxbuster updated 2 days ago and changed their path from git, now the issue is fixed :+1: 
Thanks for raising issues and Happy Hacking :100:
